
// farfetch'd and mr. mime use "slug" for API call. All other pokemon use "name".
export const pokemonList = [
    { name: 'Bulbasaur', type: 'Grass/Poison', like: 'amphibian', color: 'green', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Ivysaur', type: 'Grass/Poison', like: 'amphibian', color: 'green', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Venusaur', type: 'Grass/Poison', like: 'amphibian', color: 'green', stage: 2, hasFeet: true, canFly: false, size:"l", ears:"true" },
    { name: 'Charmander', type: 'Fire', like: 'lizard', color: 'orange', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Charmeleon', type: 'Fire', like: 'lizard', color: 'orange', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Charizard', type: 'Fire/Flying', like: 'lizard', color: 'orange', stage: 2, hasFeet: true, canFly: true, size:"l", ears:"false" },
    { name: 'Squirtle', type: 'Water', like: 'turtle', color: 'blue', stage: 0, hasFeet: true, canFly: false, size:"l", ears:"false" },
    { name: 'Wartortle', type: 'Water', like: 'turtle', color: 'blue', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Blastoise', type: 'Water', like: 'turtle', color: 'blue', stage: 2, hasFeet: true, canFly: false, size:"l", ears:"true" },
    { name: 'Caterpie', type: 'Bug/Grass', like: 'bug', color: 'green', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Metapod', type: 'Bug/Grass', like: 'bug', color: 'green', stage: 1, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Butterfree', type: 'Grass/Bug/Flying', like: 'bug', color: 'purple/white', stage: 2, hasFeet: true, canFly: true, size:"m", ears:"false" },
    { name: 'Weedle', type: 'Grass/Bug/Poison', like: 'bug', color: 'yellow/brown', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Kakuna', type: 'Grass/Bug/Poison', like: 'bug', color: 'yellow', stage: 1, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Beedrill', type: 'Grass/Bug/Poison', like: 'bug', color: 'yellow', stage: 2, hasFeet: true, canFly: true, size:"m", ears:"true" },
    { name: 'Pidgey', type: 'Normal/Flying', like: 'bird', color: 'brown', stage: 0, hasFeet: true, canFly: true, size:"s", ears:"false" },
    { name: 'Pidgeotto', type: 'Normal/Flying', like: 'bird', color: 'brown', stage: 1, hasFeet: true, canFly: true, size:"m", ears:"false" },
    { name: 'Pidgeot', type: 'Normal/Flying', like: 'bird', color: 'brown', stage: 2, hasFeet: true, canFly: true, size:"l", ears:"false" },
    { name: 'Rattata', type: 'Normal', like: 'mouse', color: 'purple', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Raticate', type: 'Normal', like: 'mouse', color: 'brown', stage: 1, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Spearow', type: 'Normal/Flying', like: 'bird', color: 'brown', stage: 0, hasFeet: true, canFly: true, size:"s", ears:"false" },
    { name: 'Fearow', type: 'Normal/Flying', like: 'bird', color: 'brown', stage: 1, hasFeet: true, canFly: true, size:"m", ears:"false" },
    { name: 'Ekans', type: 'Normal/Poison', like: 'snake', color: 'purple', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Arbok', type: 'Normal/Poison', like: 'snake', color: 'purple', stage: 1, hasFeet: false, canFly: false, size:"m/l", ears:"false" },
    { name: 'Pikachu', type: 'Electric', like: 'mouse', color: 'yellow', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Raichu', type: 'Electric', like: 'mouse', color: 'orange', stage: 1, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Sandshrew', type: 'Ground', like: 'mouse', color: 'yellow', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Sandslash', type: 'Ground', like: 'mouse', color: 'yellow', stage: 1, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Nidoran♀', slug:"nidoran-f", type: 'Normal/Poison', like: 'mouse', color: 'blue', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Nidorina', type: 'Normal/Poison', like: 'mouse', color: 'blue', stage: 1, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Nidoqueen', type: 'Poison/Ground', like: 'dino', color: 'blue', stage: 2, hasFeet: true, canFly: false, size:"l", ears:"true" },
    { name: 'Nidoran♂', slug:"nidoran-m", type: 'Normal/Poison', like: 'mouse', color: 'purple', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Nidorino', type: 'Normal/Poison', like: 'mouse', color: 'purple', stage: 1, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Nidoking', type: 'Poison/Ground', like: 'dino', color: 'purple', stage: 2, hasFeet: true, canFly: false, size:"l", ears:"true" },
    { name: 'Clefairy', type: 'Normal/Fairy', like: 'squishy and ball', color: 'pink', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Clefable', type: 'Normal/Fairy', like: 'squishy and ball', color: 'pink', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Vulpix', type: 'Fire', like: 'fox', color: 'orange/brown', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Ninetales', type: 'Fire', like: 'fox', color: 'yellow', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Jigglypuff', type: 'Normal/Fairy', like: 'squishy and ball', color: 'pink', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Wigglytuff', type: 'Normal/Fairy', like: 'squishy and ball', color: 'pink', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Zubat', type: 'Normal/Poison/Flying', like: 'bat', color: 'blue', stage: 0, hasFeet: true, canFly: true, size:"s", ears:"true" },
    { name: 'Golbat', type: 'Normal/Poison/Flying', like: 'bat', color: 'blue', stage: 1, hasFeet: true, canFly: true, size:"m", ears:"true" },
    { name: 'Oddish', type: 'Grass/Poison', like: 'plant', color: 'blue', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Gloom', type: 'Grass/Poison', like: 'plant', color: 'blue/pink', stage: 1, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Vileplume', type: 'Grass/Poison', like: 'plant', color: 'blue/pink', stage: 2, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Paras', type: 'Bug/Grass', like: 'crab', color: 'pink', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Parasect', type: 'Bug/Grass', like: 'crab', color: 'pink', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Venonat', type: 'Bug/Grass/Poison', like: 'bug', color: 'purple', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Venomoth', type: 'Bug/Grass/Poison', like: 'bug', color: 'purple', stage: 1, hasFeet: true, canFly: true, size:"m", ears:"true/false" },
    { name: 'Diglett', type: 'Ground', like: 'mole', color: 'brown', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Dugtrio', type: 'Ground', like: 'mole', color: 'brown', stage: 1, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Meowth', type: 'Normal', like: 'cat', color: 'yellow/brown', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Persian', type: 'Normal', like: 'cat', color: 'yellow/brown', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Psyduck', type: 'Water', like: 'bird', color: 'yellow', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Golduck', type: 'Water', like: 'bird', color: 'blue', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Mankey', type: 'Fighting', like: 'monkey', color: 'white/brown', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Primeape', type: 'Fighting', like: 'monkey', color: 'white/brown', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Growlithe', type: 'Fire', like: 'cat', color: 'orange', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Arcanine', type: 'Fire', like: 'cat', color: 'orange', stage: 1, hasFeet: true, canFly: false, size:"l", ears:"true" },
    { name: 'Poliwag', type: 'Water', like: 'amphibian', color: 'blue', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Poliwhirl', type: 'Water', like: 'amphibian', color: 'blue', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Poliwrath', type: 'Water/Fighting', like: 'amphibian', color: 'blue', stage: 2, hasFeet: true, canFly: false, size:"l", ears:"false" },
    { name: 'Abra', type: 'Psychic', like: 'mammal', color: 'yellow', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Kadabra', type: 'Psychic', like: 'mammal', color: 'yellow', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Alakazam', type: 'Psychic', like: 'mammal', color: 'yellow', stage: 2, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Machop', type: 'Fighting', like: 'human', color: 'blue/grey', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Machoke', type: 'Fighting', like: 'human', color: 'blue/grey', stage: 1, hasFeet: true, canFly: false, size:"l", ears:"false" },
    { name: 'Machamp', type: 'Fighting', like: 'human', color: 'blue/grey', stage: 2, hasFeet: true, canFly: false, size:"l", ears:"false" },
    { name: 'Bellsprout', type: 'Grass/Poison', like: 'plant', color: 'green/yellow', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Weepinbell', type: 'Grass/Poison', like: 'plant', color: 'green/yellow', stage: 1, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Victreebel', type: 'Grass/Poison', like: 'plant', color: 'green/yellow', stage: 2, hasFeet: false, canFly: false, size:"l", ears:"false" },
    { name: 'Tentacool', type: 'Water/Poison', like: 'jellyfish', color: 'blue', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Tentacruel', type: 'Water/Poison', like: 'jellyfish', color: 'blue', stage: 1, hasFeet: false, canFly: false, size:"l", ears:"false" },
    { name: 'Geodude', type: 'Ground', like: 'rock', color: 'brown/grey', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Graveler', type: 'Ground', like: 'rock', color: 'brown/grey', stage: 1, hasFeet: true, canFly: false, size:"l", ears:"false" },
    { name: 'Golem', type: 'Ground', like: 'rock', color: 'brown/grey', stage: 2, hasFeet: true, canFly: false, size:"l", ears:"false" },
    { name: 'Ponyta', type: 'Fire', like: 'horse', color: 'yellow', stage: 0, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Rapidash', type: 'Fire', like: 'horse', color: 'yellow', stage: 1, hasFeet: true, canFly: false, size:"l", ears:"true" },
    { name: 'Slowpoke', type: 'Water/Psychic', like: 'hippo', color: 'pink', stage: 0, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Slowbro', type: 'Water/Psychic', like: 'hippo', color: 'pink', stage: 1, hasFeet: true, canFly: false, size:"l", ears:"true" },
    { name: 'Magnemite', type: 'Electric/metal/Normal', like: 'ball', color: 'grey', stage: 0, hasFeet: false, canFly: true, size:"s", ears:"false" },
    { name: 'Magneton', type: 'Electric/metal/Normal', like: 'ball', color: 'grey', stage: 1, hasFeet: false, canFly: true, size:"m", ears:"false" },
    { name: 'Farfetch\'d', slug:"farfetchd", type: 'Normal/Flying', like: 'bird', color: 'brown', stage: 0, hasFeet: true, canFly: true, size:"m", ears:"false" },
    { name: 'Doduo', type: 'Normal/Flying', like: 'bird', color: 'brown', stage: 0, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Dodrio', type: 'Normal/Flying', like: 'bird', color: 'brown', stage: 1, hasFeet: true, canFly: false, size:"l", ears:"false" },
    { name: 'Seel', type: 'Water', like: 'seal', color: 'white', stage: 0, hasFeet: false, canFly: false, size:"m", ears:"false" },
    { name: 'Dewgong', type: 'Water/Ice', like: 'seal', color: 'white', stage: 1, hasFeet: false, canFly: false, size:"l", ears:"false" },
    { name: 'Grimer', type: 'Normal/Poison', like: 'goo', color: 'purple', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Muk', type: 'Normal/Poison', like: 'goo', color: 'purple', stage: 1, hasFeet: false, canFly: false, size:"m", ears:"false" },
    { name: 'Shellder', type: 'Water', like: 'shellfish', color: 'purple', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Cloyster', type: 'Water/Ice', like: 'shellfish', color: 'purple', stage: 1, hasFeet: false, canFly: false, size:"l", ears:"false" },
    { name: 'Gastly', type: 'Ghost/Psychic/Poison', like: 'ball', color: 'purple', stage: 0, hasFeet: false, canFly: true, size:"s", ears:"false" },
    { name: 'Haunter', type: 'Ghost/Psychic/Poison', like: 'ghost', color: 'purple', stage: 1, hasFeet: false, canFly: true, size:"m", ears:"true" },
    { name: 'Gengar', type: 'Ghost/Psychic/Poison', like: 'ghost', color: 'purple', stage: 2, hasFeet: true, canFly: true, size:"m", ears:"true" },
    { name: 'Onix', type: 'Ground', like: 'rock', color: 'grey', stage: 0, hasFeet: false, canFly: false, size:"l", ears:"false" },
    { name: 'Drowzee', type: 'Psychic', like: 'mammal', color: 'yellow', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Hypno', type: 'Psychic', like: 'mammal', color: 'yellow', stage: 1, hasFeet: true, canFly: false, size:"m/l", ears:"true" },
    { name: 'Krabby', type: 'Water', like: 'crab', color: 'pink', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Kingler', type: 'Water', like: 'crab', color: 'pink', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Voltorb', type: 'Electric', like: 'ball', color: 'pink', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Electrode', type: 'Electric', like: 'ball', color: 'pink', stage: 1, hasFeet: false, canFly: false, size:"m", ears:"false" },
    { name: 'Exeggcute', type: 'Grass/Psychic', like: 'egg', color: 'white/pink', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Exeggutor', type: 'Grass/Psychic', like: 'egg', color: 'yellow/brown', stage: 1, hasFeet: true, canFly: false, size:"l", ears:"false" },
    { name: 'Cubone', type: 'Ground', like: 'skull', color: 'brown', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Marowak', type: 'Ground', like: 'skull', color: 'brown', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Hitmonlee', type: 'Fighting', like: 'human', color: 'brown', stage: 0, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Hitmonchan', type: 'Fighting', like: 'human', color: 'brown', stage: 0, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Lickitung', type: 'Normal', like: 'lizard', color: 'pink', stage: 0, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Koffing', type: 'Normal/Poison', like: 'ball', color: 'purple', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Wheezing', type: 'Normal/Poison', like: 'ball', color: 'purple', stage: 1, hasFeet: false, canFly: false, size:"m", ears:"false" },
    { name: 'Rhyhorn', type: 'Ground', like: 'rhino', color: 'grey', stage: 0, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Rhydon', type: 'Ground', like: 'rhino', color: 'grey', stage: 1, hasFeet: true, canFly: false, size:"l", ears:"true" },
    { name: 'Chansey', type: 'Normal', like: 'squishy and ball', color: 'pink', stage: 0, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Tangela', type: 'Grass', like: 'ball', color: 'blue', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Kangaskhan', type: 'Normal', like: 'dino', color: 'brown', stage: 0, hasFeet: true, canFly: false, size:"l", ears:"true" },
    { name: 'Horsea', type: 'Water', like: 'fish', color: 'blue', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"true/false" },
    { name: 'Seadra', type: 'Water', like: 'fish', color: 'blue', stage: 1, hasFeet: false, canFly: false, size:"s", ears:"true/false" },
    { name: 'Goldeen', type: 'Water', like: 'fish', color: 'orange/white', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Seaking', type: 'Water', like: 'fish', color: 'orange', stage: 1, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Staryu', type: 'Water', like: 'fish', color: 'brown', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Starmie', type: 'Water/Psychic', like: 'fish', color: 'purple', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Mr. Mime', slug:"mr-mime", type: 'Normal/Psychic/Fairy', like: 'human', color: 'pink', stage: 0, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Scyther', type: 'Bug/Grass/Flying', like: 'bug', color: 'green', stage: 0, hasFeet: true, canFly: true, size:"m", ears:"false" },
    { name: 'Jynx', type: 'Ice/Water/Psychic', like: 'human', color: 'purple/pink', stage: 0, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Electabuzz', type: 'Electric', like: 'mammal', color: 'yellow', stage: 0, hasFeet: true, canFly: false, size:"s/m", ears:"false" },
    { name: 'Magmar', type: 'Fire', like: 'lava', color: 'orange/pink', stage: 0, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Pinsir', type: 'Bug/Grass', like: 'bug', color: 'brown', stage: 0, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Tauros', type: 'Normal', like: 'bull', color: 'brown', stage: 0, hasFeet: true, canFly: false, size:"l", ears:"false" },
    { name: 'Magikarp', type: 'Water', like: 'fish', color: 'orange', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Gyarados', type: 'Water/Flying', like: 'dino', color: 'blue', stage: 1, hasFeet: false, canFly: true, size:"l", ears:"false" },
    { name: 'Lapras', type: 'Water/Ice', like: 'dino', color: 'blue', stage: 0, hasFeet: false, canFly: false, size:"l", ears:"true" },
    { name: 'Ditto', type: 'Normal', like: 'goo', color: 'purple', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Eevee', type: 'Normal', like: 'cat', color: 'brown', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"true" },
    { name: 'Vaporeon', type: 'Water', like: 'cat/fish', color: 'blue', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Jolteon', type: 'Electric', like: 'cat', color: 'yellow', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Flareon', type: 'Fire', like: 'cat', color: 'orange', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"true" },
    { name: 'Porygon', type: 'Normal', like: 'digital', color: 'pink', stage: 0, hasFeet: true, canFly: true, size:"s/m", ears:"false" },
    { name: 'Omanyte', type: 'Ground/Water', like: 'fish', color: 'blue', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"false" },
    { name: 'Omastar', type: 'Ground/Water', like: 'fish', color: 'blue', stage: 1, hasFeet: false, canFly: false, size:"m", ears:"false" },
    { name: 'Kabuto', type: 'Ground/Water', like: 'shellfish', color: 'brown', stage: 0, hasFeet: true, canFly: false, size:"s", ears:"false" },
    { name: 'Kabutops', type: 'Ground/Water', like: 'dino', color: 'brown', stage: 1, hasFeet: true, canFly: false, size:"m", ears:"false" },
    { name: 'Aerodactyl', type: 'Ground/Flying', like: 'dino', color: 'purple', stage: 2, hasFeet: true, canFly: true, size:"l", ears:"false" },
    { name: 'Snorlax', type: 'Normal', like: 'squishy and ball', color: 'blue', stage: 0, hasFeet: true, canFly: false, size:"l", ears:"true" },
    { name: 'Articuno', type: 'Ice/Flying', like: 'bird', color: 'blue', stage: 0, hasFeet: true, canFly: true, size:"l", ears:"false" },
    { name: 'Zapdos', type: 'Electric/Flying', like: 'bird', color: 'yellow', stage: 0, hasFeet: true, canFly: true, size:"l", ears:"false" },
    { name: 'Moltres', type: 'Fire/Flying', like: 'bird', color: 'orange', stage: 0, hasFeet: true, canFly: true, size:"l", ears:"false" },
    { name: 'Dratini', type: 'Water', like: 'snake', color: 'blue', stage: 0, hasFeet: false, canFly: false, size:"s", ears:"true/false" },
    { name: 'Dragonair', type: 'Water', like: 'snake', color: 'blue', stage: 1, hasFeet: false, canFly: false, size:"m", ears:"true/false" },
    { name: 'Dragonite', type: 'Water/Flying', like: 'dragon', color: 'orange', stage: 2, hasFeet: true, canFly: true, size:"l", ears:"false" },
    { name: 'Mewtwo', type: 'Psychic', like: 'Mewtwo', color: 'purple/white', stage: 0, hasFeet: true, canFly: true, size:"l", ears:"false"  },
    { name: 'Mew', type: 'Psychic', like: 'mouse', color: 'pink', stage: 0, hasFeet: true, canFly: true, size:"s" , ears:"true"}
];

